DROP TABLE MEMBER;
DROP TABLE TEST;

CREATE TABLE TEST(
    TNO NUMBER,
    TNAME VARCHAR2(20),
    TDATE DATE
);

select * from member;

CREATE TABLE MEMBER(
    USERNO NUMBER PRIMARY KEY, -- 번호
    USERID VARCHAR2(15) NOT NULL UNIQUE, -- 아이디
    USERPWD VARCHAR2(15) NOT NULL, -- 비밀번호
    USERNAME VARCHAR2(20) NOT NULL, -- 이름
    GENDER CHAR(1) CHECK (GENDER IN ('M','F')),
    AGE NUMBER, -- 나이
    EMAIL VARCHAR2(30), -- 이메일
    PHONE CHAR(11), -- 전화번호
    ADDRESS VARCHAR2(100), -- 주소
    HOBBY VARCHAR2(50), -- 취미
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL -- 가입일
);

DROP SEQUENCE SEQ_USERNO;
CREATE SEQUENCE SEQ_USERNO
NOCACHE;

INSERT INTO MEMBER
VALUES(SEQ_USERNO.NEXTVAL, 'admin','1234','관리자','M',45,'admin@iei.or.kr','01011112222','서울', null,'2021-07-27');

INSERT INTO MEMBER
VALUES(SEQ_USERNO.NEXTVAL, 'user01','pwd01','홍길동',null,23,'user01@iei.or.kr','01022222222','부산', '등산','2021-08-07');
commit;

delete from member;
rollback;