--테이블 생성
CREATE TABLE MEMBER(
    MEM_NO INTEGER,
    MEM_ID VARCHAR(20),
    MEM_PWD VARCHAR(20),
    MEM_NAME VARCHAR(20),
    GENDER CHAR(1),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(50),
    MEM_DATE DATE
);
-- COMMENT 달기
-- 번호, 아이디, 비밀번호, 이름, 성별, 전화번호, 이메일, 회원가입일

COMMENT ON TABLE MEMBER IS '회원테이블';

COMMENT ON COLUMN MEMBER.MEM_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEM_ID IS '회원ID';
COMMENT ON COLUMN MEMBER.MEM_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.MEM_DATE IS '가입일자';

INSERT INTO MEMBER VALUES (1, 'USER1', 'PWD1','USERNAME1','M','010-2221-3331','QWER1@GMAIL.COM',SYSDATE);
INSERT INTO MEMBER VALUES (2, 'USER2', 'PWD2','USERNAME2','M','010-2222-3332','QWER2@GMAIL.COM',SYSDATE);
INSERT INTO MEMBER VALUES (3, 'USER3', 'PWD3','USERNAME3','F','010-2223-3333','QWER3@GMAIL.COM',SYSDATE);
INSERT INTO MEMBER VALUES (4, 'USER4', 'PWD4','USERNAME4','F','010-2224-3334','QWER4@GMAIL.COM',SYSDATE);
INSERT INTO MEMBER VALUES (5, 'USER5', 'PWD5','USERNAME5','M','010-2225-3335','QWER5@GMAIL.COM',SYSDATE);

-- NOT NULL
CREATE TABLE MEM_NOTNULL(
    MEM_NO INTEGER NOT NULL,
    MEM_ID VARCHAR(20) NOT NULL,
    MEM_PWD VARCHAR(20) NOT NULL,
    MEM_NAME VARCHAR(20) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(50)
);
INSERT INTO MEM_NOTNULL VALUES (1, 'USER1', 'PWD1','USERNAME1','M','010-2221-3331','QWER1@GMAIL.COM');
--INSERT INTO MEM_NOTNULL VALUES (2, 'USER2', 'PWD2','USERNAME1',NULL,'010-2221-3331','QWER1@GMAIL.COM');
INSERT INTO MEM_NOTNULL VALUES (2, 'USER2', 'PWD2','USERNAME2','M','010-2221-3331','QWER1@GMAIL.COM');

-- UNIQUE
CREATE TABLE MEM_UNIQUE(
    MEM_NO INTEGER CONSTRAINT MEM_NO_NN NOT NULL,
    MEM_ID VARCHAR(20) CONSTRAINT MEM_ID_NN NOT NULL,
    MEM_PWD VARCHAR(20) CONSTRAINT MEM_PWD_NN NOT NULL,
    MEM_NAME VARCHAR(20) CONSTRAINT MEM_NAME_NN NOT NULL,
    GENDER CHAR(1) CONSTRAINT GENDER_NN NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(50)
);

ALTER TABLE MEM_UNIQUE
ADD CONSTRAINT MEM_ID_UQ UNIQUE (MEM_ID);

