-- 1.
INSERT INTO TB_CLASS_TYPE VALUES (01,'전공필수');
INSERT INTO TB_CLASS_TYPE VALUES (02,'전공선택');
INSERT INTO TB_CLASS_TYPE VALUES (03,'교양필수');
INSERT INTO TB_CLASS_TYPE VALUES (04,'교양선택');
INSERT INTO TB_CLASS_TYPE VALUES (05,'논문지도');

SELECT * FROM TB_CLASS_TYPE;

-- 2.
CREATE TABLE TB_학생일반정보
AS (
    SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT
);

SELECT * FROM TB_학생일반정보;

-- 3.
CREATE TABLE TB_국어국문학과(학번, 학생이름, 출생년도, 교수이름)
AS (
    SELECT STUDENT_NO, STUDENT_NAME, EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RRRR')), PROFESSOR_NAME
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
    WHERE DEPARTMENT_NAME = '국어국문학과'
);

-- 4.
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY * 1.1);

-- 5.
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042' AND STUDENT_NAME = '박건우';

SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_NAME = '박건우';

-- 6.
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN,1,6);

SELECT * FROM TB_STUDENT;

-- 7.
UPDATE TB_GRADE
SET POINT = 3.5
WHERE (TERM_NO, STUDENT_NO) = (
    SELECT TERM_NO, STUDENT_NO
    FROM TB_GRADE
    JOIN TB_STUDENT S USING (STUDENT_NO)
    JOIN TB_CLASS USING (CLASS_NO)
    JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
    WHERE DEPARTMENT_NAME = '의학과' AND STUDENT_NAME = '김명훈' 
    AND TERM_NO = '200501' AND CLASS_NAME = '피부생리학'
);

SELECT STUDENT_NAME, CLASS_NAME, POINT
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE STUDENT_NAME = '김명훈';

-- 8.
DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                     FROM TB_STUDENT
                     WHERE ABSENCE_YN = 'Y');
