-- 1.
SELECT STUDENT_NO AS 학번,
    STUDENT_NAME AS 이름,
    TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') AS 입학년도
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '영어영문학과'
ORDER BY ENTRANCE_DATE;

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 3.
SELECT PROFESSOR_NAME AS 교수이름,
    CASE
        WHEN TO_CHAR(SYSDATE,'MMDD') < TO_CHAR(TO_DATE(SUBSTR(PROFESSOR_SSN,1,6)),'MMDD')
        THEN EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN,1,6))) - 1
        ELSE EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN,1,6)))
        END AS 만나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) IN (1,3);

-- 4.
SELECT SUBSTR(PROFESSOR_NAME,2,2) AS 이름
FROM TB_PROFESSOR;

-- 5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6))) > 19;

-- 6.
SELECT TO_CHAR(TO_DATE('201225'),'DAY') AS 크리스마스 FROM DUAL;

-- 7.
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'YYYY"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'RRRR"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'),'YYYY"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'),'RRRR"년" MM"월" DD"일"') FROM DUAL;

SELECT TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'),'RRRR"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'),'YYYY"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'),'RRRR"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'),'YYYY"년" MM"월" DD"일"') FROM DUAL;

-- 8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) < 2000;

-- 9 .
SELECT ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10.
SELECT DEPARTMENT_NO AS 학과번호,
    COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO;

-- 11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12.
SELECT SUBSTR(TERM_NO,1,4) AS "년도", ROUND(AVG(POINT),1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 년도;

-- 13.
SELECT DEPARTMENT_NO AS 학과코드명, 
SUM(CASE WHEN ABSENCE_YN = 'Y' THEN 1 ELSE 0 END) AS "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 14.
SELECT STUDENT_NAME AS 동일이름, COUNT(*)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) != 1
ORDER BY 동일이름;

-- 15. 
SELECT 년도, 학기 AS 학기, 학점
FROM (
    SELECT SUBSTR(TERM_NO,1,4) AS 년도, SUBSTR(TERM_NO,5,2) AS 학기, POINT AS 학점
    FROM TB_GRADE
    WHERE STUDENT_NO = 'A112113'
    UNION
    SELECT 년도, NULL AS 년도, ROUND(AVG(학점),1) AS 평점
    FROM (SELECT SUBSTR(TERM_NO,1,4) AS 년도, SUBSTR(TERM_NO,5,2) AS 학기, POINT AS 학점
            FROM TB_GRADE
            WHERE STUDENT_NO = 'A112113')
GROUP BY 년도
ORDER BY 년도, 학기 ASC
)
UNION 
SELECT NULL, NULL,ROUND(AVG(학점),1)
FROM (SELECT SUBSTR(TERM_NO,1,4) AS 년도, SUBSTR(TERM_NO,5,2) AS 학기, POINT AS 학점
    FROM TB_GRADE
    WHERE STUDENT_NO = 'A112113');

SELECT SUBSTR(TERM_NO, 1, 4) 년도, SUBSTR(TERM_NO, 5, 2) 학기, ROUND(AVG(POINT), 1) 평균
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2))
ORDER BY 1; 
